### PR TITLE
Add "-apply" flags for applying suggested fix

### LINKED ISSUE #37: Using -fix does not seem to apply fixes
I was testing this on https://github.com/fyne-io/fyne and adding `-fix` does not seem to do anything. Double checking with git just seems to indicate that no files have been changed.

image

### PR DESCRIPTION
**Pull request by cuonglm**
By using github.com/dave/dst to decorate original ast.File

Fixes #37

### CODE REVIEW

File: structslop.go [hunk 1]
```diff
@@ -119,13 +136,59 @@ func run(pass *analysis.Pass) (interface{}, error) {
 			}
 		}
 
+		dtyp := dec.Dst.Nodes[atyp].(*dst.StructType)
+		fields := make([]*dst.Field, 0, len(r.optIdx))
+		dummy := &dst.Field{}
+		for _, f := range dtyp.Fields.List {
+			fields = append(fields, f)
+			if len(f.Names) > 1 {
```
Comment (odeke-em) [inline structslop.go:144]: Let’s reduce this nesting by inverting:
if len(f.Names) <= 1 {
    continue
}

File: structslop.go [hunk 2]
```diff
@@ -119,13 +136,59 @@ func run(pass *analysis.Pass) (interface{}, error) {
...
 			Pos:            n.Pos(),
 			End:            n.End(),
 			Message:        msg,
 			SuggestedFixes: nil,
 		})
+		f := pass.Fset.File(n.Pos())
+		fileDiags[f.Name()] = suggested.Bytes()
 	})
+
+	if apply {
```
Comment (odeke-em) [inline structslop.go:174]: if !apply { return nil, nil }

File: structslop_test.go [hunk 3]
```diff
@@ -27,14 +32,45 @@ func Test(t *testing.T) {
 	analysistest.Run(t, testdata, structslop.Analyzer, "struct")
 }
 
+func TestApply(t *testing.T) {
+	dir := strings.Join([]string{".", "testdata", "src"}, string(os.PathSeparator))
```
Comment (odeke-em) [inline structslop_test.go:36]: filepath.Join(...) instead of strings.Join

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @cuonglm!

File: structslop_test.go (hunk 3 above)
Comment (cuonglm) [reply structslop_test.go:36]: This is intended. `filepath.Join` will call `Clean` before output, so relative path is cleaned.

File: structslop.go (hunk 1 above)
Comment (cuonglm) [reply structslop.go:144]: Maybe:

```
		for _, f := range dtyp.Fields.List {
			fields = append(fields, f)
			if len(f.Names) == 0 {
				continue
			}
			for range f.Names[1:] {
				fields = append(fields, dummy)
			}
		}
```

I tend to avoid `<=` or `>=`.

File: structslop.go (hunk 2 above)
Comment (cuonglm) [reply structslop.go:174]: I wonder this, too. If we invert the condition, then we have 2 `return nil, nil`, one inside `if`, one after the `for` loop.
