### PR TITLE
Fix invalid *ast.Struct construction

### LINKED ISSUE #41: index out of range crash
When running `structslop` against `pkg/sql` of [CockroachDB](https://github.com/cockroachdb/cockroach/tree/master/pkg/sql) I got the following:
```
panic: runtime error: index out of range [11] with length 10

goroutine 10501 [running]:
github.com/orijtech/structslop.run.func1(0x138cca0, 0xc006541960)
	/Users/yuzefovich/go/pkg/mod/github.com/orijtech/structslop@v0.0.4/structslop.go:98 +0xbf2
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc02cc427a0, 0xc004e81b20, 0x1, 0x1, 0xc004f6fb30)
	/Users/yuzefovich/go/pkg/mod/golang.org/x/tools@v0.0.0-20200917221617-d56e4e40bc9d/go/ast/inspector/inspector.go:77 +0xa2
github.com/orijtech/structslop.run(0xc02cc400c0, 0xc02cc400c0, 0x0, 0x0, 0x0)
	/Users/yuzefovich/go/pkg/mod/github.com/orijtech/structslop@v0.0.4/structslop.go:68 +0x1fa
golang.org/x/tools/go/analysis/internal/checker.(*action).execOnce(0xc02ec706e0)
	/Users/yuzefovich/go/pkg/mod/golang.org/x/tools@v0.0.0-20200917221617-d56e4e40bc9d/go/analysis/internal/checker/checker.go:690 +0x87e
sync.(*Once).doSlow(0xc02ec706e0, 0xc00004f790)
	/usr/local/opt/go/libexec/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/opt/go/libexec/src/sync/once.go:57
golang.org/x/tools/go/analysis/internal/checker.(*action).exec(0xc02ec706e0)
	/Users/yuzefovich/go/pkg/mod/golang.org/x/tools@v0.0.0-20200917221617-d56e4e40bc9d/go/analysis/internal/checker/checker.go:579 +0x65
golang.org/x/tools/go/analysis/internal/checker.execAll.func1(0xc02ec706e0)
	/Users/yuzefovich/go/pkg/mod/golang.org/x/tools@v0.0.0-20200917221617-d56e4e40bc9d/go/analysis/internal/checker/checker.go:567 +0x34
created by golang.org/x/tools/go/analysis/internal/checker.execAll
	/Users/yuzefovich/go/pkg/mod/golang.org/x/tools@v0.0.0-20200917221617-d56e4e40bc9d/go/analysis/internal/checker/checker.go:573 +0x125
```

### PR DESCRIPTION
**Pull request by cuonglm**
Currently, we compose new *ast.StructType for pretty print optimal
struct. But *ast.StructType can compose multiple fields of the same type
into one element of *ast.StructType.Fields, causing mismatch with the
optimal indexes.

To fix this, we format new optimal struct as before, then parsing the
returned string to compose new *ast.StructType instead.

Fixes #41

### CODE REVIEW

File: testdata/src/struct/p.go [hunk 1]
```diff
@@ -34,11 +34,10 @@ type s3 struct { // want `struct has size 24 \(size class 32\), could be 16 \(si
 }
 
 type s4 struct { // want `struct has size 40 \(size class 48\), could be 24 \(size class 32\), you'll save 33.33% if you rearrange it to:\nstruct {\n\t_  \[0\]func\(\)\n\ti1 int\n\ti2 int\n\ta3 \[3\]bool\n\tb  bool\n}`
-	b  bool
-	i1 int
-	i2 int
-	a3 [3]bool
-	_  [0]func()
+	b      bool
```
Comment (odeke-em) [inline testdata/src/struct/p.go:37]: Perhaps let’s add this sample as s9 separately so that we have a clear case of different samples.

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @cuonglm for the fix. However I’ve made a suggestion to add a separate test case as s9.

File: testdata/src/struct/p.go (hunk 1 above)
Comment (cuonglm) [reply testdata/src/struct/p.go]: Fixed.
